export const MUSK_VS_ZUCK_VOTING_PROGRAM_ID_TESTNET = "4Hb5C8M17BvMtmRoGccMhNcVtsE581abLcgpNdeHbXDp";
export const MUSK_VS_ZUCK_VOTING_PROGRAM_ID_MAINNET = "";
export const MUSK_VS_ZUCK_VOTING_PROGRAM_ID_LOCALHOST = "";
export const BATTLE_ACCOUNT_TESTNET = "DecWJwByta3GGRKPL2voACehQsoH2W51r4ZA65baQorL";
export const BATTLE_ACCOUNT_MAINNET = "";
